[auth]
redirect_uri = "https://space.fptoj.com/oauth2callback"
cookie_secret = "Spgg2r4HHGal37TH4uvcsubbfJ_nv3IEHgF7ezLtiBU"

client_id = "1024648143321-1setg692pba89cvfatnvbm2mlmj0s3ap.apps.googleusercontent.com"
client_secret = "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"
server_metadata_url = "https://accounts.google.com/.well-known/openid-configuration"
